[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
# Enable Pyflakes, pycodestyle, and isort rules.
lint.select = ["E", "F", "W", "I"]
line-length = 88

# Ignore certain rules if needed, e.g., E501 (line too long), which black handles.
lint.ignore = ["E501"]

[lint.per-file-ignores]
"__init__.py" = ["F401"] # Ignore unused imports in __init__.py files
