name: Insider Bot Twice Daily

on:
  schedule:
    # Germany: run ~1 hour after US market open (approx 15:30 UTC summer / 14:30 UTC winter)
    # and ~1 hour before close (approx 20:00 UTC). Adjust as needed.
    - cron: '30 15 * * 1-5'
    - cron: '0 20 * * 1-5'
  workflow_dispatch:
    inputs:
      timepoint:
        description: Time horizon (e.g., 1w)
        required: false
        default: '1w'
      tp:
        description: Take-profit (e.g., 0.10)
        required: false
        default: '0.10'
      sl:
        description: Stop-loss (e.g., -0.10)
        required: false
        default: '-0.10'
      threshold:
        description: Label threshold percent (e.g., 1)
        required: false
        default: '1'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alpaca-trade-api==3.2.0 --no-deps

      - name: Configure environment
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_API_SECRET_KEY: ${{ secrets.ALPACA_API_SECRET_KEY }}
          GOOGLE_SHEET_CREDS_JSON: ${{ secrets.GOOGLE_SHEET_CREDS_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          echo "ALPACA_API_KEY set: ${#ALPACA_API_KEY} chars"
          echo "Google creds present: ${{ env.GOOGLE_SHEET_CREDS_JSON != '' }}"

      - name: Run bot (workflow_dispatch overrides, else defaults)
        run: |
          TIMEPOINT='1w'
          TP='0.10'
          SL='-0.10'
          THRESHOLD='1'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TIMEPOINT='${{ inputs.timepoint }}'
            TP='${{ inputs.tp }}'
            SL='${{ inputs.sl }}'
            THRESHOLD='${{ inputs.threshold }}'
          fi
          echo "Args: $TIMEPOINT $TP $SL thr=$THRESHOLD"
          python run_bot.py --timepoint "$TIMEPOINT" --tp "$TP" --sl "$SL" --threshold_pct "$THRESHOLD" --lookback_days 2 --gate 0.6

      - name: Upload signals
        uses: actions/upload-artifact@v4
        with:
          name: signals
          path: results/bot/*.parquet


